### ISSUE TITLE
Example code does not build

### ISSUE THREAD

**Issue by ZeroSumGame** [b1naryth1ef/dscord#18]
> ../src/dscord/bot/command.d(43,3): Error: closures are not yet supported in CTFE
src/basic.d(33,22):        called from here: CommandDescription("HI")
dmd failed with exit code 1.

More importantly:
>../src/dscord/bot/listener.d(23,45): Error: delegate dscord.bot.plugin.Plugin.Listenable!().loadListeners!(BasicPlugin).loadListeners.__lambda1 cannot get frame pointer to dscord.bot.listener.Listener!(VoiceStateUpdate).Listener.__lambda2
dmd failed with exit code 1.

Other listener code also does not work as exposed, such as your [Creating Plugins  Wiki Entry](https://github.com/b1naryth1ef/jeff/wiki/Creating-Plugins):
```
@Listener!MessageCreate()
void onMessageCreate(MessageCreate event) {
  this.log.infof("A message was created: %s", event);
}
```
This throws an error essentially the same as the one for listener.d(23,45) as above.

Commands are the only examples that currently do build in dmd-2.027.2, leaving audio and message listeners dead in the water.

**Comment by b1naryth1ef** [comment]
Fixed by #17
