### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by TheGag96** [b1naryth1ef/dscord#11]
I tried compiling on Windows using DMD v2.071.1 (so 32-bit binary by default) and I got this:

`
..\..\..\AppData\Roaming\dub\packages\fast-master\fast\source\fast\json.d(1475,9): Error: static assert  "Not implemented"
..\..\..\AppData\Roaming\dub\packages\fast-master\fast\source\fast\json.d(97,1):        instantiated from here: Json!(0u, false)
`

It seems fast's JSON library doesn't support Windows at the moment... Until that changes or a different library is used, this library is unfortunately Linux/OS X only.

**Comment by srhinos** [comment]
Not sure if he said it anywhere on Github but on Discord hes said it a few times that this library wouldn't compile on Windows under any circumstance. :(

**Comment by TheGag96** [comment]
That's a real shame... Why was it designed this way? (And you do mean "this library" as dscord and not fast, right?)

**Comment by b1naryth1ef** [comment]
Because windows is a terrible platform. This libraries specific intention is to provide an extremely fast and efficient interface to Discord, one that can be used to build extremely large bots without the need to shard extensively. Windows is both a terrible platform for development, and also extremely slow, inconsistent and inefficient. Although its entirely possible I could add support for this in the future through version guarding, it was not an initial design goal, and nothing something that's currently on my roadmap.

**Comment by b1naryth1ef** [comment]
Should compile fine on windows in 0.0.9
